apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: hami-cluster-queue
spec:
  namespaceSelector: {} # Match all namespaces
  resourceGroups:
  - coveredResources: ["nvidia.com/gpu", "nvidia.com/gpumem", "nvidia.com/gpucores"]
    flavors:
    - name: hami-vgpu-flavor
      resources:
      - name: "nvidia.com/gpu"
        nominalQuota: 10 # E.g., 10 GPUs in the cluster
      - name: "nvidia.com/gpumem"
        nominalQuota: 80000 # E.g., 80GB total vGPU memory in the cluster
      - name: "nvidia.com/gpucores"
        nominalQuota: 100 # E.g., 100% total vGPU core capacity
