# .github/release.yml
changelog:
  exclude:
    labels:
    - ignore-for-release
    - github-actions
    authors:
    - dependabot[bot]
  categories:
  - title: ✨ New Features
    labels:
    - feature
    - design
    - enhancement
  - title: 🐛 Bug Fixes
    labels:
    - bug
  - title: 📚 Documentation
    labels:
    - documentation
  - title: ⬆️ Dependencies
    labels:
    - dependencies
  - title: 💥 Breaking Changes
    labels:
    - breaking-change
  - title: 🔨 Other Changes
    labels:
    - "*"
