
SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c


INSTALL = install

PREFIX?=/usr
BINDIR?=$(PREFIX)/bin
TARGETARCH ?= amd64

DESTDIR_BIN ?= $(ROOT_DIR)/output/$(TARGETARCH)/bin
DESTDIR_BASH_COMPLETION ?= $(ROOT_DIR)/output/$(TARGETARCH)/bash-completion

VERSION = $(shell cat $(dir $(lastword $(MAKEFILE_LIST)))/VERSION)

ECHO_GEN=echo "  GEN   $(RELATIVE_DIR)/"