// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/api/device_register.proto

package api

// Reference imports to suppress errors if they are not otherwise used.

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
type DeviceInfo struct {
	Index   int
	Id      string
	Count   int32
	Devmem  int32
	Devcore int32
	Type    string
	Numa    int
	Health  bool
}
