apiVersion: v1
kind: Pod
metadata:
  name: ascend910b3-job
spec:
  containers:
    - name: ubuntu-container
      image: ascendhub.huawei.com/public-ascendhub/ascend-mindspore:23.0.RC3-centos7
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          huawei.com/Ascend910B3: 1 # requesting 1 NPU
          huawei.com/Ascend910B3-memory: 2000 # requesting 2000m device memory