apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 2 # Declare how many physical GPUs the pod needs
          nvidia.com/gpumem: 3000 # Identifies 3000M GPU memory each physical GPU allocates to the pod （Optional,Integer）
          nvidia.com/gpucores: 30 # Identifies 30% GPU GPU core each physical GPU allocates to the pod （Optional,Integer)
