// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
type InterfaceMock struct {
	// AdditionalDevicesFunc mocks the AdditionalDevices method.
	AdditionalDevicesFunc func() []string

	// CreateMigSpecFileFunc mocks the CreateMigSpecFile method.
	CreateMigSpecFileFunc func(migUUID string, devicePath string, caps map[string]string) error

	// CreateSpecFileFunc mocks the CreateSpecFile method.
	CreateSpecFileFunc func() error

	// DeleteMigSpecFileFunc mocks the DeleteMigSpecFile method.
	DeleteMigSpecFileFunc func(migUUID string) error

	// QualifiedNameFunc mocks the QualifiedName method.
	QualifiedNameFunc func(s1 string, s2 string) string

	// calls tracks calls to the methods.
	calls struct {
		// AdditionalDevices holds details about calls to the AdditionalDevices method.
		AdditionalDevices []struct {
		}
		// CreateMigSpecFile holds details about calls to the CreateMigSpecFile method.
		CreateMigSpecFile []struct {
			// MigUUID is the migUUID argument value.
			MigUUID string
			// DevicePath is the devicePath argument value.
			DevicePath string
			// Caps is the caps argument value.
			Caps map[string]string
		}
		// CreateSpecFile holds details about calls to the CreateSpecFile method.
		CreateSpecFile []struct {
		}
		// DeleteMigSpecFile holds details about calls to the DeleteMigSpecFile method.
		DeleteMigSpecFile []struct {
			// MigUUID is the migUUID argument value.
			MigUUID string
		}
		// QualifiedName holds details about calls to the QualifiedName method.
		QualifiedName []struct {
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
	}
	lockAdditionalDevices sync.RWMutex
	lockCreateMigSpecFile sync.RWMutex
	lockCreateSpecFile    sync.RWMutex
	lockDeleteMigSpecFile sync.RWMutex
	lockQualifiedName     sync.RWMutex
}

// AdditionalDevices calls AdditionalDevicesFunc.
func (mock *InterfaceMock) AdditionalDevices() []string {
	callInfo := struct {
	}{}
	mock.lockAdditionalDevices.Lock()
	mock.calls.AdditionalDevices = append(mock.calls.AdditionalDevices, callInfo)
	mock.lockAdditionalDevices.Unlock()
	if mock.AdditionalDevicesFunc == nil {
		var (
			stringsOut []string
		)
		return stringsOut
	}
	return mock.AdditionalDevicesFunc()
}

// AdditionalDevicesCalls gets all the calls that were made to AdditionalDevices.
func (mock *InterfaceMock) AdditionalDevicesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAdditionalDevices.RLock()
	calls = mock.calls.AdditionalDevices
	mock.lockAdditionalDevices.RUnlock()
	return calls
}

// CreateMigSpecFile calls CreateMigSpecFileFunc.
func (mock *InterfaceMock) CreateMigSpecFile(migUUID string, devicePath string, caps map[string]string) error {
	callInfo := struct {
		MigUUID    string
		DevicePath string
		Caps       map[string]string
	}{
		MigUUID:    migUUID,
		DevicePath: devicePath,
		Caps:       caps,
	}
	mock.lockCreateMigSpecFile.Lock()
	mock.calls.CreateMigSpecFile = append(mock.calls.CreateMigSpecFile, callInfo)
	mock.lockCreateMigSpecFile.Unlock()
	if mock.CreateMigSpecFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateMigSpecFileFunc(migUUID, devicePath, caps)
}

// CreateMigSpecFileCalls gets all the calls that were made to CreateMigSpecFile.
func (mock *InterfaceMock) CreateMigSpecFileCalls() []struct {
	MigUUID    string
	DevicePath string
	Caps       map[string]string
} {
	var calls []struct {
		MigUUID    string
		DevicePath string
		Caps       map[string]string
	}
	mock.lockCreateMigSpecFile.RLock()
	calls = mock.calls.CreateMigSpecFile
	mock.lockCreateMigSpecFile.RUnlock()
	return calls
}

// CreateSpecFile calls CreateSpecFileFunc.
func (mock *InterfaceMock) CreateSpecFile() error {
	callInfo := struct {
	}{}
	mock.lockCreateSpecFile.Lock()
	mock.calls.CreateSpecFile = append(mock.calls.CreateSpecFile, callInfo)
	mock.lockCreateSpecFile.Unlock()
	if mock.CreateSpecFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateSpecFileFunc()
}

// CreateSpecFileCalls gets all the calls that were made to CreateSpecFile.
func (mock *InterfaceMock) CreateSpecFileCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCreateSpecFile.RLock()
	calls = mock.calls.CreateSpecFile
	mock.lockCreateSpecFile.RUnlock()
	return calls
}

// DeleteMigSpecFile calls DeleteMigSpecFileFunc.
func (mock *InterfaceMock) DeleteMigSpecFile(migUUID string) error {
	callInfo := struct {
		MigUUID string
	}{
		MigUUID: migUUID,
	}
	mock.lockDeleteMigSpecFile.Lock()
	mock.calls.DeleteMigSpecFile = append(mock.calls.DeleteMigSpecFile, callInfo)
	mock.lockDeleteMigSpecFile.Unlock()
	if mock.DeleteMigSpecFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteMigSpecFileFunc(migUUID)
}

// DeleteMigSpecFileCalls gets all the calls that were made to DeleteMigSpecFile.
func (mock *InterfaceMock) DeleteMigSpecFileCalls() []struct {
	MigUUID string
} {
	var calls []struct {
		MigUUID string
	}
	mock.lockDeleteMigSpecFile.RLock()
	calls = mock.calls.DeleteMigSpecFile
	mock.lockDeleteMigSpecFile.RUnlock()
	return calls
}

// QualifiedName calls QualifiedNameFunc.
func (mock *InterfaceMock) QualifiedName(s1 string, s2 string) string {
	callInfo := struct {
		S1 string
		S2 string
	}{
		S1: s1,
		S2: s2,
	}
	mock.lockQualifiedName.Lock()
	mock.calls.QualifiedName = append(mock.calls.QualifiedName, callInfo)
	mock.lockQualifiedName.Unlock()
	if mock.QualifiedNameFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.QualifiedNameFunc(s1, s2)
}

// QualifiedNameCalls gets all the calls that were made to QualifiedName.
func (mock *InterfaceMock) QualifiedNameCalls() []struct {
	S1 string
	S2 string
} {
	var calls []struct {
		S1 string
		S2 string
	}
	mock.lockQualifiedName.RLock()
	calls = mock.calls.QualifiedName
	mock.lockQualifiedName.RUnlock()
	return calls
}
