/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The HAMi Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

/*
 * Licensed to NVIDIA CORPORATION under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. NVIDIA CORPORATION licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * Modifications Copyright The HAMi Authors. See
 * GitHub history for details.
 */

// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cdi

import (
	"sync"
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//	func TestSomethingThatUsesInterface(t *testing.T) {
//
//		// make and configure a mocked Interface
//		mockedInterface := &InterfaceMock{
//			AdditionalDevicesFunc: func() []string {
//				panic("mock out the AdditionalDevices method")
//			},
//			CreateSpecFileFunc: func() error {
//				panic("mock out the CreateSpecFile method")
//			},
//			QualifiedNameFunc: func(s1 string, s2 string) string {
//				panic("mock out the QualifiedName method")
//			},
//		}
//
//		// use mockedInterface in code that requires Interface
//		// and then make assertions.
//
//	}
type InterfaceMock struct {
	// AdditionalDevicesFunc mocks the AdditionalDevices method.
	AdditionalDevicesFunc func() []string

	// CreateSpecFileFunc mocks the CreateSpecFile method.
	CreateSpecFileFunc func() error

	// QualifiedNameFunc mocks the QualifiedName method.
	QualifiedNameFunc func(s1 string, s2 string) string

	// calls tracks calls to the methods.
	calls struct {
		// AdditionalDevices holds details about calls to the AdditionalDevices method.
		AdditionalDevices []struct {
		}
		// CreateSpecFile holds details about calls to the CreateSpecFile method.
		CreateSpecFile []struct {
		}
		// QualifiedName holds details about calls to the QualifiedName method.
		QualifiedName []struct {
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
	}
	lockAdditionalDevices sync.RWMutex
	lockCreateSpecFile    sync.RWMutex
	lockQualifiedName     sync.RWMutex
}

// AdditionalDevices calls AdditionalDevicesFunc.
func (mock *InterfaceMock) AdditionalDevices() []string {
	callInfo := struct {
	}{}
	mock.lockAdditionalDevices.Lock()
	mock.calls.AdditionalDevices = append(mock.calls.AdditionalDevices, callInfo)
	mock.lockAdditionalDevices.Unlock()
	if mock.AdditionalDevicesFunc == nil {
		var (
			stringsOut []string
		)
		return stringsOut
	}
	return mock.AdditionalDevicesFunc()
}

// AdditionalDevicesCalls gets all the calls that were made to AdditionalDevices.
// Check the length with:
//
//	len(mockedInterface.AdditionalDevicesCalls())
func (mock *InterfaceMock) AdditionalDevicesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockAdditionalDevices.RLock()
	calls = mock.calls.AdditionalDevices
	mock.lockAdditionalDevices.RUnlock()
	return calls
}

// CreateSpecFile calls CreateSpecFileFunc.
func (mock *InterfaceMock) CreateSpecFile() error {
	callInfo := struct {
	}{}
	mock.lockCreateSpecFile.Lock()
	mock.calls.CreateSpecFile = append(mock.calls.CreateSpecFile, callInfo)
	mock.lockCreateSpecFile.Unlock()
	if mock.CreateSpecFileFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateSpecFileFunc()
}

// CreateSpecFileCalls gets all the calls that were made to CreateSpecFile.
// Check the length with:
//
//	len(mockedInterface.CreateSpecFileCalls())
func (mock *InterfaceMock) CreateSpecFileCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCreateSpecFile.RLock()
	calls = mock.calls.CreateSpecFile
	mock.lockCreateSpecFile.RUnlock()
	return calls
}

// QualifiedName calls QualifiedNameFunc.
func (mock *InterfaceMock) QualifiedName(s1 string, s2 string) string {
	callInfo := struct {
		S1 string
		S2 string
	}{
		S1: s1,
		S2: s2,
	}
	mock.lockQualifiedName.Lock()
	mock.calls.QualifiedName = append(mock.calls.QualifiedName, callInfo)
	mock.lockQualifiedName.Unlock()
	if mock.QualifiedNameFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.QualifiedNameFunc(s1, s2)
}

// QualifiedNameCalls gets all the calls that were made to QualifiedName.
// Check the length with:
//
//	len(mockedInterface.QualifiedNameCalls())
func (mock *InterfaceMock) QualifiedNameCalls() []struct {
	S1 string
	S2 string
} {
	var calls []struct {
		S1 string
		S2 string
	}
	mock.lockQualifiedName.RLock()
	calls = mock.calls.QualifiedName
	mock.lockQualifiedName.RUnlock()
	return calls
}
