/*
Copyright 2024 The HAMi Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package cdi

import (
	cdiparser "tags.cncf.io/container-device-interface/pkg/parser"
)

// DefaultVendor is the CDI vendor used by the NVIDIA device plugin. It matches
// the vendor of the CDI specs generated by the NVIDIA Container Toolkit /
// GPU Operator (e.g. /var/run/cdi/k8s.device-plugin.nvidia.com-gpu.json).
const DefaultVendor = "k8s.device-plugin.nvidia.com"

// externalHandler is a CDI handler for nodes where the accelerator is exposed
// only through externally-managed CDI specs and NVML is not available to the
// device plugin. This is the case for CDI-only accelerators such as the GB10
// (Grace-Blackwell iGPU), whose device is described by a CDI spec generated by
// the NVIDIA Container Toolkit rather than being enumerable via NVML.
//
// It can construct qualified CDI device names for injection but does not
// generate CDI spec files itself (the spec is provided by the node).
type externalHandler struct {
	vendor string
}

var _ Interface = &externalHandler{}

// newExternalHandler returns a CDI handler that references externally-managed
// CDI specs. An empty vendor defaults to DefaultVendor.
func newExternalHandler(vendor string) Interface {
	if vendor == "" {
		vendor = DefaultVendor
	}
	return &externalHandler{vendor: vendor}
}

// CreateSpecFile is a no-op: the CDI spec is managed externally on the node.
func (h *externalHandler) CreateSpecFile() error {
	return nil
}

// QualifiedName constructs a CDI qualified device name for the specified
// resources. It assumes the id matches a device name present in the
// externally-managed CDI spec.
func (h *externalHandler) QualifiedName(class string, id string) string {
	return cdiparser.QualifiedName(h.vendor, class, id)
}

// AdditionalDevices returns no additional devices for externally-managed specs.
func (h *externalHandler) AdditionalDevices() []string {
	return nil
}
