# request 1g DRS profile
apiVersion: v1
kind: Pod
metadata:
  name: vgcu-pod-1
  namespace: kube-system
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: pod-gcu-example1
      image: ubuntu:18.04
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - '100000'
      resources:
        limits:
          enflame.com/drs-gcu: 1
        requests:
          enflame.com/drs-gcu: 1
---
# request 3g DRS profile
apiVersion: v1
kind: Pod
metadata:
  name: vgcu-pod-2
  namespace: kube-system
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: pod-gcu-example1
      image: ubuntu:18.04
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - '100000'
      resources:
        limits:
          enflame.com/drs-gcu: 3
        requests:
          enflame.com/drs-gcu: 3
---
# request by memory/core, HAMi converts to DRS profile automatically
apiVersion: v1
kind: Pod
metadata:
  name: drs-pod-by-spec
  namespace: kube-system
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: pod-gcu-example1
      image: ubuntu:18.04
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - '100000'
      resources:
        limits:
          enflame.com/gcu-memory: 20480
          enflame.com/gcu-core: 40
        requests:
          enflame.com/gcu-memory: 20480
          enflame.com/gcu-core: 40