apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "4pd-vgpu.scheduler" . }}
  labels:
    app.kubernetes.io/component: 4pd-scheduler
    {{- include "4pd-vgpu.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations }}
  annotations: {{ toYaml .Values.global.annotations | nindent 4}}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: 4pd-scheduler
      {{- include "4pd-vgpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: 4pd-scheduler
        {{- include "4pd-vgpu.selectorLabels" . | nindent 8 }}
        4pd.io/webhook: ignore
      {{- if .Values.scheduler.podAnnotations }}
      annotations: {{ toYaml .Values.scheduler.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- include "4pd-vgpu.imagePullSecrets" . | nindent 6}}
      serviceAccountName: {{ include "4pd-vgpu.scheduler" . }}
      priorityClassName: system-node-critical
      containers:
        - name: kube-scheduler
          image: {{ .Values.scheduler.kubeScheduler.image | quote }}
          imagePullPolicy: {{ .Values.scheduler.kubeScheduler.imagePullPolicy | quote }}
          command:
            - kube-scheduler
            - --policy-config-file=/config/config.json
            - --leader-elect=false
            - --scheduler-name={{ .Values.schedulerName }}
            {{- range .Values.scheduler.kubeScheduler.extraArgs }}
            - {{ . }}
            {{- end }}
          volumeMounts:
            - name: scheduler-config
              mountPath: /config
        - name: vgpu-scheduler-extender
          image: {{ .Values.scheduler.extender.image | quote }}
          imagePullPolicy: {{ .Values.scheduler.extender.imagePullPolicy | quote }}
          command:
            - scheduler
            - --resource-name={{ .Values.resourceName }}
            - --resource-mem={{ .Values.resourceMem }}
            - --resource-cores={{ .Values.resourceCores }}
            - --http_bind=0.0.0.0:443
            - --grpc_bind=0.0.0.0:1080
            - --cert_file=/tls/tls.crt
            - --key_file=/tls/tls.key
            - --scheduler-name={{ .Values.schedulerName }}
            {{- range .Values.scheduler.extender.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 443
              protocol: TCP
            - name: grpc
              containerPort: 1080
              protocol: TCP
          volumeMounts:
            - name: tls-config
              mountPath: /tls
      volumes:
        - name: tls-config
          secret:
            secretName: {{ template "4pd-vgpu.scheduler.tls" . }}
        - name: scheduler-config
          configMap:
            name: {{ template "4pd-vgpu.scheduler" . }}
      {{- if .Values.scheduler.nodeSelector }}
      nodeSelector: {{ toYaml .Values.scheduler.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.scheduler.tolerations }}
      tolerations: {{ toYaml .Values.scheduler.tolerations | nindent 8 }}
      {{- end }}
