apiVersion: batch/v1
kind: Job
metadata:
  name: ai-benchmark-on-official
spec:
  template:
    metadata:
      name: ai-benchmark-on-official
    spec:
      containers:
        - name: ai-benchmark-on-official
          image: 4pdosc/ai-benchmark:2.4.1-gpu
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never