apiVersion: apps/v1
kind: Deployment
metadata:
  name: binpack-1
  labels:
    app: binpack-1
spec:
  replicas: 2
  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: binpack-1
  template: # define the pods specifications
    metadata:
      labels:
        app: binpack-1
    spec:
      containers:
        - name: c-1
          image: ubuntu:18.04
          command: ["sleep"]
          args: ["100000"]
          lifecycle:                                                       # 必需
            #postStart:                                                     # 必需
            #  exec:                                                        # 必需
            #    command: ["/bin/sh", "-c", "/usr/bin/smlu-containerd"]     # 必需
          resources:
            limits:
              cambricon.com/mlunum: 1
              cambricon.com/mlumem: 10240                                   # 设置 MLU 内存
        - name: c-2
          image: ubuntu:18.04
          command: ["sleep"]
          args: ["100000"]
          lifecycle:                                                       # 必需
            #postStart:                                                     # 必需
            #  exec:                                                        # 必需
            #    command: ["/bin/sh", "-c", "/usr/bin/smlu-containerd"]     # 必需
          resources:
            limits:
              cambricon.com/mlunum: 1
              cambricon.com/mlumem: 10240                                   # 设置 MLU 内存