apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  annotations:
    cambricon.com/use-mlutype: "270" # Specify the card type for this job, use comma to seperate, will not launch job on non-specified card
    #In this example, we want to run this job on 270 or 370
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          cambricon.com/mlunum: 1
          cambricon.com/mlumem: 10240 
