apiVersion: batch/v1
kind: Job
metadata:
  name: ai-benchmark
spec:
  template:
    metadata:
      name: ai-benchmark
    spec:
      containers:
        - name: ai-benchmark
          image: 4pdosc/ai-benchmark:2.4.1-gpu
          resources:
            requests:
              nvidia.com/gpu: 1
              nvidia.com/gpumem-percentage: 50
            limits:
              nvidia.com/gpu: 1
              nvidia.com/gpumem-percentage: 50
      restartPolicy: Never