{{- if .Values.devices.ascend.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hami-vgpu.fullname" . }}-ascend-device-plugin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: hami-ascend-device-plugin
    {{- include "hami-vgpu.labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.global.annotations }}
  annotations: {{ toYaml .Values.global.annotations | nindent 4}}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hami-ascend-device-plugin
      {{- include "hami-vgpu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hami-ascend-device-plugin
        hami.io/webhook: ignore
        {{- include "hami-vgpu.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: "system-node-critical"
      serviceAccountName: {{ include "hami-vgpu.fullname" . }}-ascend
      containers:
        - image: {{ .Values.devices.ascend.image }}
          imagePullPolicy: {{ .Values.devices.ascend.imagePullPolicy | quote }}
          name: device-plugin
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 500m
          args:
            - --config_file
            - /ascend-config.yaml
            {{- range .Values.devices.ascend.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: pod-resource
              mountPath: /var/lib/kubelet/pod-resources
            - name: hiai-driver
              mountPath: /usr/local/Ascend/driver
              readOnly: true
            - name: log-path
              mountPath: /var/log/mindx-dl/devicePlugin
            - name: tmp
              mountPath: /tmp
            - name: device-config
              mountPath: /ascend-config.yaml
              subPath: ascend-config.yaml
              readOnly: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: pod-resource
          hostPath:
            path: /var/lib/kubelet/pod-resources
        - name: hiai-driver
          hostPath:
            path: /usr/local/Ascend/driver
        - name: log-path
          hostPath:
            path: /var/log/mindx-dl/devicePlugin
            type: Directory
        - name: tmp
          hostPath:
            path: /tmp
        - name: device-config
          configMap:
            name: {{ include "hami-vgpu.scheduler" . }}-device
      {{- if .Values.devices.ascend.nodeSelector }}
      nodeSelector: {{ toYaml .Values.devices.ascend.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.devices.ascend.tolerations }}
      tolerations: {{ toYaml .Values.devices.ascend.tolerations | nindent 8 }}
      {{- end }}
{{- end }}