{{- if .Values.devices.ascend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.fullname" . }}-ascend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "hami-ascend"
    {{- include "hami-vgpu.labels" . | nindent 4 }}
{{- end }}