apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "4pd-vgpu.device-plugin" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: "4pd-device-plugin"
    {{- include "4pd-vgpu.labels" . | nindent 4 }}
