apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "4pd-vgpu.device-plugin" . }}
  labels:
    app.kubernetes.io/component: "4pd-device-plugin"
    {{- include "4pd-vgpu.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  #name: cluster-admin
  name: {{ include "4pd-vgpu.device-plugin" . }}-monitor
subjects:
  - kind: ServiceAccount
    name: {{ include "4pd-vgpu.device-plugin" . }}
    namespace: {{ .Release.Namespace | quote }}
