apiVersion: v1
kind: Pod
metadata:
  name: vhcu-pytorch-demo
  annotations:
    hygon.com/use-hcutype: "HCU-K100_AI" #Specify the card type for this job, use comma to separate, will launch job on specified card
    #In this example, we  want this container to run on K100_AI
spec:
  containers:
    - name: vhcu-pytorch-demo
      image: image.sourcefind.cn:5000/hcu/admin/base/pytorch:2.1.0-ubuntu22.04-dtk24.04.2-py3.10
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "sleep infinity & wait" ]
      resources:
        limits:
          hygon.com/hcunum: 1
          hygon.com/hcucores: 60
          hygon.com/hcumem: 2000
