apiVersion: v1
kind: Pod
metadata:
  name: alexnet-tf-gpu-pod-mem
  annotations:
    hygon.com/use-dcutype: "Z100" # Specify the card type for this job, use comma to separate, will not launch job on non-specified card
    #In this example, we want to run this job on Z100
  labels:
    purpose: demo-tf-amdgpu
spec:
  containers:
    - name: alexnet-tf-gpu-container
      image: pytorch:resnet50
      workingDir: /root
      command: ["sleep","infinity"]
      resources:
        limits:
          hygon.com/dcunum: 1 # requesting a GPU
          hygon.com/dcumem: 2000
          hygon.com/dcucores: 60
