{{- include "hami-vgpu.validateDeviceValues" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hami-vgpu.scheduler" . }}-device
  namespace: {{ include "hami-vgpu.namespace" . }}
  labels:
    app.kubernetes.io/component: hami-scheduler
    {{- include "hami-vgpu.labels" . | nindent 4 }}
data:
  device-config.yaml: |-
    {{- include "hami-vgpu.deviceConfig" . | nindent 4 }}
