{
 "title": "hami-vgpu-metrics-dashboard",
 "description": "This dashboard is gpu metrics dashboard base on NVIDIA DCGM Exporter and HAMi/k8s-vgpu-scheduler This dashboard is gpu metrics dashboard base on NVIDIA DCGM Exporter and HAMi/k8s-vgpu-scheduler, and was modified from https://grafana.com/grafana/dashboards/21833-hami-vgpu-dashboard/ ",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": {
     "query": "label_values({__name__=~\"DCGM_FI_DEV_FB_FREE|vgpu_device_memory_limit_bytes\"}, node_name)"
    }
   },
   {
    "name": "uuid",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_FREE{node_name=~\"$node_name\"},UUID)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_DEC_UTIL{node_name=~\"${node_name}\",UUID=~\"${uuid}\"})"
    }
   ]
  },
  {
   "title": "XID Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_values(\"DCGM_FI_DEV_XID_ERRORS\", DCGM_FI_DEV_XID_ERRORS{node_name=~\"${node_name}\",UUID=~\"${uuid}\"} > 0)) or on() vector(0)"
    }
   ]
  },
  {
   "title": "Average GPU Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{node_name=~\"${node_name}\",UUID=~\"${uuid}\"})"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{node_name=~\"${node_name}\",UUID=~\"${uuid}\"})"
    }
   ]
  },
  {
   "title": "GPU temp(DCGM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{node_name=~\"${node_name}\",UUID=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{UUID}}"
    }
   ]
  },
  {
   "title": "Node GPU Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "node_gpu_overview{nodeid=~\"${node_name}\",deviceuuid=~\"${uuid}\"}"
    }
   ]
  },
  {
   "title": "nodeGPUList(DCGM)",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{node_name=~\"${node_name}\", UUID=~\"${uuid}\"}"
    }
   ]
  },
  {
   "title": "vGPUCorePercentage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deviceuuid, nodename) (vGPUCorePercentage{nodename=~\"${node_name}\"})",
     "legendFormat": " {{nodename}}:{{deviceuuid}}"
    }
   ]
  },
  {
   "title": "GPU FB used(DCGM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{node_name=~\"${node_name}\", UUID=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{UUID}}"
    }
   ]
  },
  {
   "title": "GPU util(DCGM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{node_name=~\"${node_name}\", UUID=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{UUID}}"
    }
   ]
  },
  {
   "title": "vGPUMemoryPercentage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deviceuuid, nodename) (vGPUMemoryPercentage{nodename=~\"${node_name}\"})",
     "legendFormat": "{{nodename}}:{{deviceuuid}}"
    }
   ]
  },
  {
   "title": "GPU power usage(DCGM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{node_name=~\"${node_name}\",UUID=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{UUID}}"
    }
   ]
  },
  {
   "title": "GPU SM Clock(DCGM)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{node_name=~\"${node_name}\", UUID=~\"${uuid}\"} * 1000000",
     "legendFormat": "{{node_name}} uid:{{UUID}}"
    }
   ]
  },
  {
   "title": "vgpu used by nodes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (node_name) (vgpu_device_memory_limit_bytes{node_name=~\"${node_name}\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "HAMi-Memory desc of container ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (podname) (Device_memory_desc_of_container{node_name=~\"${node_name}\",deviceuuid=~\"${uuid}\"})",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "HAMi-GPU util  desc of container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (podname) (Device_utilization_desc_of_container{node_name=~\"${node_name}\",deviceuuid=~\"${uuid}\"})",
     "legendFormat": "{{podname}}"
    }
   ]
  },
  {
   "title": "HAMi-Host memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "host_gpu_memory_usage_bytes{node_name=~\"${node_name}\",deviceuuid=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{deviceuuid}}"
    }
   ]
  },
  {
   "title": "HAMi-Host core util",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "HostCoreUtilization{node_name=~\"${node_name}\",deviceuuid=~\"${uuid}\"}",
     "legendFormat": "{{node_name}} uid:{{deviceuuid}}"
    }
   ]
  }
 ]
}