{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.mcp-server" . }}
  namespace: {{ include "hami-vgpu.namespace" . }}
  labels:
    app.kubernetes.io/component: "hami-mcp-server"
    {{- include "hami-vgpu.labels" . | nindent 4 }}
{{- end }}
