name: latest image to DockerHub
on:
  push:
    branches:
      - master

env:
  GO_VERSION: "1.21.6"

jobs:
  build:
    name: build-dev-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # We need to guess version via git tags.
          fetch-depth: 0
      - name: Checkout submodule
        uses: Mushus/checkout-submodule@v1.0.1
        with:
          basePath: # optional, default is .
          submodulePath: libvgpu

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_TOKEN }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - run: make tidy
      - run: SHORT_VERSION="dev" bash ./hack/build.sh