name: 'issue-translate'
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  translate: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          IS_MODIFY_TITLE: true
          BOT_GITHUB_TOKEN: ${{ secrets.TRANSLATE_ROBOT_TOKEN }}
