name: 'issue-translate'
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  translate: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: tomsun28/issues-translate-action@b41f55ddc81d7d54bd542a4f289fe28ec081898e # v2.7
        with:
          IS_MODIFY_TITLE: true
          BOT_GITHUB_TOKEN: ${{ secrets.TRANSLATE_ROBOT_TOKEN }}
